### ISSUE TITLE
Avoid security leakage and enable other people to use the client

### ISSUE THREAD

**Issue by longqua69** [kngan79/crawl-data-project#1]
Hardcoding credentials local file https://github.com/kngan79/crawl-data-project/blob/main/crawl_luongthangnet.py#L11-L17 blocks other users utilize this script and can lead to security issue. Should change to use hidden configs or environment variables instead

**Comment by kngan79** [comment]
thanks @longqua69 for your comment, I've created the env variable already to hide the credential path

**Comment by longqua69** [comment]
Good start, though, open a Pull Request to handle issue instead of committing and merging right on the main branch next time
